# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
			${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "telechips-topst-bsp"
BBFILE_PATTERN_telechips-topst-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_telechips-topst-bsp = "8"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_telechips-topst-bsp = "2"
LAYERDEPENDS_telechips-topst-bsp = "core"
LAYERSERIES_COMPAT_telechips-topst-bsp = "kirkstone"

LICENSE_PATH += "${LAYERDIR}/licenses"

COMPATIBLE_LICENSES:append = " ARM"
IMAGE_FEATURES[validitems] += "uboot-fit"

SDK_VENDOR = "-topst"

# Set Telechips git
TELECHIPS_TOPST_GIT ??= "git://github.com/topst-development"

TOPST_GIT_PROTOCOL ??= "https"
TOPST_BRANCH ??= "develop"

# Add preferred versions
PREFERRED_VERSION_mesa ?= "22.%"
PREFERRED_VERSION_wayland ?= "1.20.0"
PREFERRED_VERSION_wayland-native ?= "1.20.0"
PREFERRED_VERSION_nativesdk-wayland ?= "1.20.0"
PREFERRED_VERSION_weston ?= "10.%"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-topst"
PREFERRED_VERSION_linux-topst = "${LINUX_VERSION}"
PREFERRED_VERSION_linux-libc-headers = "${LINUXLIBCVERSION}"

PREFERRED_PROVIDER_virtual/libomxil ?= "libomxil-telechips"
VIRTUAL-RUNTIME_libomxil ?= "libomxil-telechips"

PREFERRED_PROVIDER_virtual/crypt ?= "glibc"
PREFERRED_PROVIDER_virtual/nativesdk-crypt ?= "nativesdk-glibc"

# Set gcc version
GCCVERSION ?= "arm-11.2"

DEFAULT_USER_NAME ?= "topst"
DEFAULT_GROUP_NAME ?= "topst"
DEFAULT_PASSWORD ?= "topst"
DEFAULT_ROOT_PASSWORD ?= "root"

# Exclude recipes from being cleared by rm_work
RM_WORK_EXCLUDE += " \
		u-boot-topst initramfs-topst-image linux-topst kernel-devsrc boot-firmware hsm \
		tc-enable-removable-disk topst-vpu hsm \
		telechips-egl mesa powervr powervr-app t-media-framework \
		gstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
"
OPENGL_SAMPLE_APP:tcc805x = "${@bb.utils.contains('TCC_BSP_FEATURES', 'drm', 'powervr-app kmscube', 'powervr-app gles-samples', d)}"
OPENGL_SAMPLE_APP:tcc807x = "${@bb.utils.contains('TCC_BSP_FEATURES', 'drm', 'kmscube', 'tc-teapot-light', d)}"
OPENGL_SAMPLE_APP:tcc750x = ""
